version: '2'
services:
  postgres:
    image: postgres
  rabbitmq:
    image: rabbitmq
  elasticsearch:
    image: elasticsearch
  web:
    build: .
    image: bugapp
    command: ["./wait-for-it.sh", "postgres:5432", "--",
              "./wait-for-it.sh", "rabbitmq:5672", "--",
              "./wait-for-it.sh", "elasticsearch:9200", "--",
              "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/bugApp
    ports:
      - "3000:3000"
    links:
      - postgres
      - rabbitmq
      - elasticsearch
  sneakers:
    image: bugapp
    command: ["./wait-for-it.sh", "postgres:5432", "--",
              "./wait-for-it.sh", "rabbitmq:5672", "--",
              "./wait-for-it.sh", "elasticsearch:9200", "--",
              "rake", "sneakers:run"]
    depends_on:
      - web
  db_creation:
    image: bugapp
    command: ["./wait-for-it.sh", "postgres:5432", "--",
              "./wait-for-it.sh", "rabbitmq:5672", "--",
              "./wait-for-it.sh", "elasticsearch:9200", "--",
              "rake", "db:create"]
    depends_on:
      - web
  db_migration:
    image: bugapp
    command: ["./wait-for-it.sh", "postgres:5432", "--",
              "./wait-for-it.sh", "rabbitmq:5672", "--",
              "./wait-for-it.sh", "elasticsearch:9200", "--",
              "rake", "db:migrate"]
    depends_on:
      - db_creation
