version: '2'
services:
  postgres:
    image: postgres:9.4
  rabbitmq:
    image: rabbitmq:3-management
  bugapp:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bugApp
    ports:
      - "3000:3000"
    links:
      - rabbitmq
      - postgres
